# This is a basic workflow to help you get started with Actions

name: e2e-testing-qa - CI Trigger testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  

    steps:
        - name: e2e-testing-qa repo - Set up Python
          uses: actions/setup-python@v2
          with:
              python-version: "3.9"
        
        - name: e2e-testing-qa repo - Display Python version
          run: python -c "import sys; print(sys.version)"
        
        - name: e2e-testing-qa repo - Deploy
          run: echo "e2e-testing-qa repo -  deploy job completed."
    
        - name: e2e-testing-qa repo - E2E
          run: echo "e2e-testing-qa repo - E2E job completed."
